version: '3.5'

services:

  php-cli:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ~/.composer:/root/.composer/cache

  # mongo
  mongo:
    image: mongo:3.4-xenial
    environment:
      MONGO_DATA_DIR: /var/www/html/data/cache
      MONGO_INITDB_ROOT_USERNAME: demo
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./data/cache:/var/www/html/data/cache
    ports:
      - 27017:27017
    command: mongod --smallfiles

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: demo
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret