<div class="col-md-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><?= $this->title; ?></h3>
        </div>
        <div class="panel-body">
            <p><?= $this->content; ?></p>

            <p>
                <a class="btn btn-success pull-right" href="http://framework.zend.com/" target="_blank">ZF Development
                    Portal &raquo;</a>
            </p>
        </div>
    </div>
</div>